### ISSUE TITLE
兄弟  为什么会被微信封啊

### ISSUE THREAD

**Issue by cyruschueng** [zhaozhantao/levelstar#1]

**Comment by zhaozhantao** [comment]
因为之前在放在开源中国gitee上的pages，发现微信打不开，微信提示如果我是站长就在根节点放一个.txt文件代表我是站长，然后再联系解封，我就试了一下，发现不行，应该是说的gitee.com的根节点，我显然不是gitee的站长，所以后来就用github的pages了。
